project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    title: false
    left: 
      - text: "Home"
        file: index.qmd
    right: 
      - text: "Dashboard"
        file: "http://localhost:5008"  
      - text: "Background"
        file: background.qmd
      - text: "About Us"
        file: analysis/about-us.qmd
      - icon: github
        href: https://github.com/musa-550-fall-2024/24fall-python-final-christina_sara_final
format:
  html:
    theme: cosmo

execute:
  kernel: python
  cache: false  
  echo: false   
  results: 'hide' 
